// fuzz_seed_corpus — write real decks for libFuzzer to start from.
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Usage: cargo run -p decks-core --example fuzz_seed_corpus -- fuzz/corpus
//
// See the companion in letters-core for why the seeds are generated by this
// suite's own writers rather than committed as binaries.

use decks_core::engine::{Deck, Slide, SlideObject};
use letters_core::model::{Run, RunStyle};
use std::path::{Path, PathBuf};

fn text_box(x: f64, y: f64, text: &str, runs: Vec<Run>) -> SlideObject {
    SlideObject::TextBox { x, y, w: 300.0, h: 80.0, text: text.to_string(), runs, rotation: 0.0 }
}

/// Decks chosen for the reader branches they reach, not for looking real.
fn decks() -> Vec<(&'static str, Deck)> {
    let mut out = Vec::new();

    out.push(("empty", Deck::default()));

    let mut one = Deck::default();
    if let Some(slide) = one.slides.first_mut() {
        slide.objects.push(text_box(40.0, 40.0, "A title on one slide", Vec::new()));
    }
    out.push(("one-text-box", one));

    // Several slides, so slide ordering and per-slide relationship
    // resolution are both exercised.
    let many = Deck {
        slides: (0..4)
            .map(|index| Slide {
                title: format!("Slide {index}"),
                background: String::new(),
                objects: vec![text_box(40.0, 40.0, &format!("Slide {index}"), Vec::new())],
                notes: format!("Speaker notes for slide {index}"),
                master_idx: None,
            })
            .collect(),
        ..Deck::default()
    };
    out.push(("four-slides-with-notes", many));

    // Styled runs and shapes: the geometry and run-style paths.
    let mut shapes = Deck::default();
    if let Some(slide) = shapes.slides.first_mut() {
        slide.objects.push(text_box(
            20.0,
            20.0,
            "bold italic",
            vec![
                Run { text: "bold ".into(), style: RunStyle { bold: true, ..Default::default() } },
                Run { text: "italic".into(), style: RunStyle { italic: true, ..Default::default() } },
            ],
        ));
        slide.objects.push(SlideObject::Rect {
            x: 60.0, y: 160.0, w: 120.0, h: 90.0, rotation: 0.0,
        });
        slide.objects.push(SlideObject::Circle {
            x: 260.0, y: 200.0, r: 45.0, rotation: 0.0,
        });
    }
    out.push(("shapes-and-runs", shapes));

    let mut unicode = Deck::default();
    if let Some(slide) = unicode.slides.first_mut() {
        slide.objects.push(text_box(
            40.0, 40.0,
            "héllo \u{4e16}\u{754c} e\u{301} \u{1f4dd} & < > \" '",
            Vec::new(),
        ));
    }
    out.push(("unicode", unicode));

    out
}

fn write_seed(dir: &Path, name: &str, bytes: &[u8]) {
    std::fs::create_dir_all(dir).expect("create corpus directory");
    let path = dir.join(name);
    std::fs::write(&path, bytes).expect("write seed");
    println!("{} ({} bytes)", path.display(), bytes.len());
}

/// A seed the reader rejects is a wasted starting point. See the companion
/// in letters-core.
fn verify(readable: &mut usize, label: &str, ok: bool) {
    if ok {
        *readable += 1;
    } else {
        eprintln!("seed is not readable by its own reader: {label}");
        std::process::exit(1);
    }
}

fn main() {
    let root = PathBuf::from(
        std::env::args().nth(1).unwrap_or_else(|| "fuzz/corpus".to_string()),
    );

    let mut readable = 0usize;

    for (name, deck) in decks() {
        if let Ok(bytes) = decks_core::odp::write_bytes(&deck) {
            let tmp = tempfile::Builder::new().suffix(".odp").tempfile().expect("tempfile");
            std::fs::write(tmp.path(), &bytes).expect("stage the odp");
            let staged = tmp.path().to_str().expect("utf-8 temp path");
            verify(&mut readable, &format!("{name}.odp"), decks_core::odp::read(staged).is_ok());
            write_seed(&root.join("decks_odp"), &format!("{name}.odp"), &bytes);
        }

        let tmp = tempfile::Builder::new().suffix(".pptx").tempfile().expect("tempfile");
        let path = tmp.path().to_str().expect("utf-8 temp path");
        if decks_core::engine::write_pptx(path, &deck).is_ok() {
            let bytes = std::fs::read(path).expect("read back the pptx");
            verify(
                &mut readable,
                &format!("{name}.pptx"),
                decks_core::engine::read_pptx(path).is_ok(),
            );
            write_seed(&root.join("decks_pptx"), &format!("{name}.pptx"), &bytes);

            // parse_master_shapes takes raw XML, so its corpus is the slide
            // XML pulled back out of a package this suite wrote.
            if let Ok(file) = std::fs::File::open(path) {
                if let Ok(mut archive) = zip::ZipArchive::new(file) {
                    for part in ["ppt/slides/slide1.xml", "ppt/slideMasters/slideMaster1.xml"] {
                        use std::io::Read;
                        if let Ok(mut entry) = archive.by_name(part) {
                            let mut xml = String::new();
                            if entry.read_to_string(&mut xml).is_ok() {
                                let leaf = part.rsplit('/').next().unwrap_or("part.xml");
                                // parse_master_shapes is infallible by
                                // signature, so reaching a return at all is
                                // what there is to check.
                                let _ = decks_core::engine::parse_master_shapes(&xml);
                                readable += 1;
                                write_seed(
                                    &root.join("decks_master_shapes"),
                                    &format!("{name}-{leaf}"),
                                    xml.as_bytes(),
                                );
                            }
                        }
                    }
                }
            }
        }
    }

    println!("{readable} generated seed(s) verified readable by their own readers");
}
