// fuzz_seed_corpus — write real workbooks for libFuzzer to start from.
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Usage: cargo run -p tables-core --example fuzz_seed_corpus -- fuzz/corpus
//
// See the companion in letters-core for why the seeds are generated by this
// suite's own writers rather than committed as binaries.

use std::path::{Path, PathBuf};
use tables_core::engine::TablesEngine;
use tables_core::sheet::SheetModel;

fn sheet_from(
    name: &str,
    sheet_id: u32,
    cells: &[(usize, usize, &str)],
) -> Result<SheetModel, String> {
    const ROWS: usize = 24;
    const COLS: usize = 10;
    let mut engine = TablesEngine::new(ROWS, COLS)?;
    for (row, col, value) in cells {
        engine.set_cell_text(*row, *col, value);
    }
    engine.evaluate();
    let mut sheet = SheetModel::new(name, ROWS, COLS, sheet_id);
    sheet.sync_from_engine(&engine);
    Ok(sheet)
}

/// Workbooks chosen for the reader branches they reach.
fn workbooks() -> Vec<(&'static str, Vec<SheetModel>)> {
    let mut out: Vec<(&'static str, Vec<SheetModel>)> = Vec::new();

    if let Ok(s) = sheet_from("Empty", 1, &[]) {
        out.push(("empty", vec![s]));
    }

    // Values, formulas that reference them, and an error — three different
    // cached-value shapes in the sheet XML.
    if let Ok(s) = sheet_from(
        "Values",
        1,
        &[
            (0, 0, "Region"), (0, 1, "Q1"), (0, 2, "Q2"),
            (1, 0, "North"), (1, 1, "1200"), (1, 2, "=B2*2"),
            (2, 0, "South"), (2, 1, "950.25"), (2, 2, "=SUM(B2:B3)"),
            (3, 0, "Bad"), (3, 1, "=1/0"), (3, 2, "=UNKNOWNFN(1)"),
        ],
    ) {
        out.push(("values-and-formulas", vec![s]));
    }

    // More than one sheet, so workbook.xml's relationship resolution and the
    // per-sheet part lookup both have something to resolve.
    if let (Ok(a), Ok(b)) = (
        sheet_from("First", 1, &[(0, 0, "one"), (1, 0, "=A1&\" two\"")]),
        sheet_from("Second", 2, &[(0, 0, "other sheet")]),
    ) {
        out.push(("two-sheets", vec![a, b]));
    }

    if let Ok(s) = sheet_from(
        "Unicode",
        1,
        &[
            (0, 0, "héllo"),
            (0, 1, "\u{4e16}\u{754c}"),
            (0, 2, "e\u{301} \u{1f4dd}"),
            (1, 0, "& < > \" '"),
        ],
    ) {
        out.push(("unicode", vec![s]));
    }

    out
}

fn write_seed(dir: &Path, name: &str, bytes: &[u8]) {
    std::fs::create_dir_all(dir).expect("create corpus directory");
    let path = dir.join(name);
    std::fs::write(&path, bytes).expect("write seed");
    println!("{} ({} bytes)", path.display(), bytes.len());
}

/// A seed the reader rejects is a wasted starting point. See the companion
/// in letters-core.
fn verify(readable: &mut usize, label: &str, ok: bool) {
    if ok {
        *readable += 1;
    } else {
        eprintln!("seed is not readable by its own reader: {label}");
        std::process::exit(1);
    }
}

fn main() {
    let root = PathBuf::from(
        std::env::args().nth(1).unwrap_or_else(|| "fuzz/corpus".to_string()),
    );

    let mut readable = 0usize;

    for (name, sheets) in workbooks() {
        let tmp = tempfile::Builder::new().suffix(".xlsx").tempfile().expect("tempfile");
        let path = tmp.path().to_str().expect("utf-8 temp path");
        if tables_core::io::save_sheets_to_xlsx(path, &sheets).is_ok() {
            let bytes = std::fs::read(path).expect("read back the xlsx");
            verify(
                &mut readable,
                &format!("{name}.xlsx"),
                tables_core::io::load_xlsx_workbook(path).is_ok(),
            );
            // Both xlsx targets take the same package: `tables_xlsx` reads it
            // as a workbook, `tables_xlsx_parts` as the three best-effort
            // part readers. libFuzzer keeps a corpus per target, so the seed
            // is written to both rather than shared.
            write_seed(&root.join("tables_xlsx"), &format!("{name}.xlsx"), &bytes);
            write_seed(&root.join("tables_xlsx_parts"), &format!("{name}.xlsx"), &bytes);
        }
    }

    // ODS has no writer in this suite — Tables reads it and saves as xlsx on
    // purpose (#439). The committed fixtures are the only real ODS files
    // here, so they are the seeds, and saying so is better than leaving the
    // ods target to start from noise without explanation.
    let fixtures = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    if let Ok(entries) = std::fs::read_dir(&fixtures) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "ods") {
                if let Ok(bytes) = std::fs::read(&path) {
                    let name = path.file_name().unwrap().to_string_lossy().to_string();
                    verify(
                        &mut readable,
                        &name,
                        tables_core::io::load_ods_workbook(path.to_str().unwrap()).is_ok(),
                    );
                    write_seed(&root.join("tables_ods"), &name, &bytes);
                }
            }
        }
    }

    println!("{readable} generated seed(s) verified readable by their own readers");
}
