blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/tuna-os/gtk-office-suite/blob/main/SECURITY.md
    about: Please don't report security problems in a public issue.
