// fuzz_seed_corpus — write real documents for libFuzzer to start from.
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Usage: cargo run -p letters-core --example fuzz_seed_corpus -- fuzz/corpus
//
// Why this exists: libFuzzer with no corpus starts from an empty input and
// mutates upward, and a document package is a ZIP — it needs a local header,
// a central directory, and a matching CRC before a reader looks at a single
// byte of XML. Reaching that by chance inside a bounded nightly run does not
// happen, so the package targets were spending their whole budget failing to
// produce a readable archive. A measurement from the deterministic harness
// puts the scale of it: mutating a *valid* package leaves only about a
// quarter of seeds readable, and that is starting from something correct.
//
// So the seeds are generated by this suite's own writers rather than
// committed as binaries. They cannot drift from the format the writers
// actually produce, they stay reviewable (this file is the fixture), and
// the repository keeps its no-binary-fixtures property.

use letters_core::model::{Document, ParaStyle, Paragraph, Run, RunStyle, TableCell};
use std::path::{Path, PathBuf};

fn styled(text: &str, style: RunStyle) -> Run {
    Run { text: text.to_string(), style }
}

/// Documents chosen to cover the branches a reader takes, not to look
/// realistic: a seed's value is the code path it reaches.
fn documents() -> Vec<(&'static str, Document)> {
    let mut out = Vec::new();

    out.push(("plain", Document::from_plain_text("A plain letter with two lines.\nSecond line.")));
    out.push(("empty", Document::from_plain_text("")));

    let mut rich = Document::from_plain_text("");
    rich.paragraphs = vec![
        Paragraph {
            style: ParaStyle { heading: Some(1), ..Default::default() },
            runs: vec![styled("A heading", RunStyle::default())],
        },
        Paragraph {
            style: ParaStyle::default(),
            runs: vec![
                styled("bold ", RunStyle { bold: true, ..Default::default() }),
                styled("italic ", RunStyle { italic: true, ..Default::default() }),
                styled("underlined ", RunStyle { underline: true, ..Default::default() }),
                styled("struck ", RunStyle { strikethrough: true, ..Default::default() }),
                styled("code", RunStyle { code: true, ..Default::default() }),
            ],
        },
        Paragraph {
            style: ParaStyle::default(),
            runs: vec![styled(
                "a link",
                RunStyle { link: Some("https://example.invalid/x".into()), ..Default::default() },
            )],
        },
    ];
    out.push(("rich-runs", rich));

    // A table: the structure #532 lived in, and the one with the most
    // invariants for a reader to violate.
    let mut table = Document::from_plain_text("");
    table.paragraphs = (0..2)
        .flat_map(|row| {
            (0..3).map(move |col| Paragraph {
                style: ParaStyle {
                    table_cell: Some(TableCell { table: 1, row, col }),
                    ..Default::default()
                },
                runs: vec![Run {
                    text: format!("r{row}c{col}"),
                    style: RunStyle::default(),
                }],
            })
        })
        .collect();
    out.push(("table-2x3", table));

    // Text a byte-level mutator turns into interesting encodings: multi-byte
    // UTF-8, a combining mark, an astral-plane character, and an entity that
    // must survive escaping.
    out.push((
        "unicode",
        Document::from_plain_text("héllo \u{4e16}\u{754c} e\u{301} \u{1f4dd} & < > \" '"),
    ));

    out
}

fn write_seed(dir: &Path, name: &str, bytes: &[u8]) {
    std::fs::create_dir_all(dir).expect("create corpus directory");
    let path = dir.join(name);
    std::fs::write(&path, bytes).expect("write seed");
    println!("{} ({} bytes)", path.display(), bytes.len());
}

/// A seed the reader rejects is a wasted starting point — libFuzzer would
/// spend its budget mutating something that never reached the parser. So
/// every seed is read back before it counts, and a writer change that makes
/// the corpus unreadable fails this generator rather than quietly halving
/// the value of the nightly run.
fn verify(readable: &mut usize, label: &str, ok: bool) {
    if ok {
        *readable += 1;
    } else {
        eprintln!("seed is not readable by its own reader: {label}");
        std::process::exit(1);
    }
}

fn main() {
    let root = PathBuf::from(
        std::env::args().nth(1).unwrap_or_else(|| "fuzz/corpus".to_string()),
    );
    let mut readable = 0usize;

    for (name, doc) in documents() {
        // ODT goes through a path-taking writer, so it needs a real file.
        let tmp = tempfile::Builder::new().suffix(".odt").tempfile().expect("tempfile");
        let path = tmp.path().to_str().expect("utf-8 temp path");
        if letters_core::odt::write(&doc, path).is_ok() {
            let bytes = std::fs::read(path).expect("read back the odt");
            verify(&mut readable, &format!("{name}.odt"), letters_core::odt::read(path).is_ok());
            write_seed(&root.join("letters_odt"), &format!("{name}.odt"), &bytes);
        }

        // DOCX: the OOXML half of the same document set.
        let tmp = tempfile::Builder::new().suffix(".docx").tempfile().expect("tempfile");
        let path = tmp.path().to_str().expect("utf-8 temp path");
        if letters_core::docx::write(&doc, path).is_ok() {
            let bytes = std::fs::read(path).expect("read back the docx");
            verify(&mut readable, &format!("{name}.docx"), letters_core::docx::read(path).is_ok());
            write_seed(&root.join("letters_docx"), &format!("{name}.docx"), &bytes);
        }

        // markdown::parse takes &str, so its corpus is text. It is infallible
        // by signature, so "readable" here means it produced a document
        // rather than that it returned Ok.
        let markdown = letters_core::markdown::serialize(&doc);
        let parsed = letters_core::markdown::parse(&markdown);
        verify(&mut readable, &format!("{name}.md"), !parsed.paragraphs.is_empty() || markdown.is_empty());
        write_seed(&root.join("letters_markdown"), &format!("{name}.md"), markdown.as_bytes());
    }

    // The CommonMark corpus is already vendored for the round-trip tests and
    // is a far better markdown seed set than anything written by hand: 652
    // examples chosen by the spec authors to cover its own edge cases.
    let spec = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/corpus/commonmark-spec.json");
    if let Ok(text) = std::fs::read_to_string(&spec) {
        if let Ok(examples) = serde_json::from_str::<Vec<serde_json::Value>>(&text) {
            for (index, example) in examples.iter().enumerate() {
                if let Some(markdown) = example.get("markdown").and_then(|v| v.as_str()) {
                    write_seed(
                        &root.join("letters_markdown"),
                        &format!("commonmark-{index:04}.md"),
                        markdown.as_bytes(),
                    );
                }
            }
        }
    }

    println!("{readable} generated seed(s) verified readable by their own readers");
}
