#!/usr/bin/env python3
"""Generate README's per-app status table from the render-lab scorecard (#1211).

RENDER-PARITY-ROADMAP.md, "Rules the humans enforce in review", rule 3:
README status is generated from the scorecard, so the table cannot claim
more than the fixtures support. The table used to be hand-written. It still
said lists appear as literal "- " text weeks after every list fixture went
green, and nothing would have stopped it claiming the opposite either.

The scorecard is `tools/render-lab/baseline.json` plus, for the real
documents, `tools/render-lab/baseline-real.json`: the per-fixture,
per-tier verdicts that the render-parity workflow ratchets `summary.json`
against, so the two cannot disagree on a merged commit. `--summary` reads a
lab run's `summary.json` instead.

An app is "usable for everyday documents" only when every gate holds:

  single-feature  every fixture green in Tiers A and B, except the ambers
                  accepted as metric artifacts in RENDER-PARITY-ROADMAP.md;
  real documents  the Phase 3 corpus (fixtures named <app>/real-…) is
                  measured and green (#1200);
  shipped build   every fixture green in Tier C, the installed Flatpak on a
                  real GNOME VM (#1199).

Usage:
  readme_status.py            print the table
  readme_status.py --write    rewrite the README block in place
  readme_status.py --check    exit 1 if README's block differs (CI)
"""

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BASELINE = os.path.join(ROOT, "tools", "render-lab", "baseline.json")
# The real-document corpus ratchets separately (real_corpus/README.md).
BASELINE_REAL = os.path.join(ROOT, "tools", "render-lab", "baseline-real.json")
README = os.path.join(ROOT, "README.md")
BEGIN = "<!-- render-status:begin (generated by tools/render-lab/readme_status.py; do not edit) -->"
END = "<!-- render-status:end -->"
APPS = (("letters", "Letters"), ("tables", "Tables"), ("decks", "Decks"))

# Accepted metric artifacts, each recorded with its measurement under
# "Known metric artifacts" in docs/RENDER-PARITY-ROADMAP.md (#1198). Adding
# one here is a review decision, not a way to turn a gate green.
ACCEPTED_AMBER = {"letters/table", "tables/number-formats", "tables/wrap-text"}


def load(summary=None, baseline=BASELINE, baseline_real=BASELINE_REAL):
    """{fixture: {tier: verdict}} from a summary.json, or the baseline and
    the real-document baseline (when it exists) together."""
    if summary:
        with open(summary) as f:
            data = json.load(f)
        return {fx["fixture"]: dict(fx.get("verdicts", {})) for fx in data["fixtures"]}
    with open(baseline) as f:
        verdicts = json.load(f)
    if os.path.exists(baseline_real):
        with open(baseline_real) as f:
            verdicts.update(json.load(f))
    return verdicts


def app_row(app, verdicts):
    mine = {k: v for k, v in verdicts.items() if k.startswith(app + "/")}
    single = {k: v for k, v in mine.items() if not k.startswith(app + "/real-")}
    real = {k: v for k, v in mine.items() if k.startswith(app + "/real-")}

    def green(v, tiers):
        return all(v.get(t) == "green" for t in tiers)

    ab_green = sorted(k for k, v in single.items() if green(v, "AB"))
    accepted = sorted(k for k, v in single.items() if not green(v, "AB") and k in ACCEPTED_AMBER
                      and all(v.get(t) in ("green", "amber") for t in "AB"))
    failing = sorted(set(single) - set(ab_green) - set(accepted))
    cell = f"{len(ab_green)} / {len(single)} green"
    if accepted:
        cell += " + " + ", ".join(f"`{k}` (accepted amber)" for k in accepted)
    if failing:
        cell += "; not green: " + ", ".join(f"`{k}`" for k in failing)
    single_ok = bool(single) and not failing

    if real:
        real_green = sum(1 for v in real.values() if green(v, "AB"))
        real_cell = f"{real_green} / {len(real)} green"
        real_ok = real_green == len(real)
    else:
        real_cell, real_ok = "not measured yet (#1200)", False

    in_c = {k: v for k, v in mine.items() if "C" in v}
    if in_c:
        c_green = sum(1 for v in in_c.values() if v["C"] == "green")
        c_cell = f"{c_green} / {len(mine)} green"
        c_ok = c_green == len(mine)
    else:
        c_cell, c_ok = "not measured yet (#1199)", False

    usable = single_ok and real_ok and c_ok
    status = "**Usable for everyday documents**" if usable else "Not yet usable for everyday documents"
    return cell, real_cell, c_cell, status


def table(verdicts):
    lines = [
        "| App | Single-feature fixtures, Tiers A and B | Real documents | Shipped Flatpak (Tier C) | Status |",
        "|---|---|---|---|---|",
    ]
    for app, name in APPS:
        cell, real, c, status = app_row(app, verdicts)
        lines.append(f"| **{name}** | {cell} | {real} | {c} | {status} |")
    return "\n".join(lines)


def block(verdicts):
    return f"{BEGIN}\n{table(verdicts)}\n{END}"


def readme_block(text):
    try:
        start = text.index(BEGIN)
        end = text.index(END, start) + len(END)
    except ValueError:
        return None, None, None
    return text[start:end], start, end


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--summary", help="a render-lab summary.json instead of the baseline")
    ap.add_argument("--readme", default=README)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)

    want = block(load(args.summary))
    if not (args.write or args.check):
        print(want)
        return 0
    with open(args.readme) as f:
        text = f.read()
    have, start, end = readme_block(text)
    if have is None:
        print(f"{args.readme}: no generated status block ({BEGIN!r} … {END!r})", file=sys.stderr)
        return 1
    if args.check:
        if have != want:
            print("README's status table does not match the render-lab scorecard. "
                  "Run tools/render-lab/readme_status.py --write and commit README.md.", file=sys.stderr)
            return 1
        print("README status table matches the scorecard.")
        return 0
    with open(args.readme, "w") as f:
        f.write(text[:start] + want + text[end:])
    return 0


if __name__ == "__main__":
    sys.exit(main())
